# this will override /etc/nix/nix.conf, 
# generated by modules/nixos/shared/nix.nix
# managed by nix-darwin or nixos, when using them with home-manager
# adding the configuration below at ~/.config/nix/nix.conf
{ flake, pkgs, lib, ... }:

{
  nix = {
    package = lib.mkDefault (pkgs.nix);
    nixPath = [ "nixpkgs=${flake.inputs.nixpkgs}" ]; # Enables use of `nix-shell -p ...` etc
    registry.nixpkgs.flake = flake.inputs.nixpkgs; # Make `nix shell` etc use pinned nixpkgs
    settings = {
      build-users-group = lib.mkDefault "nixbld";
      auto-optimise-store = false;
      experimental-features = "nix-command flakes auto-allocate-uids";
      extra-platforms = lib.mkIf pkgs.stdenv.isDarwin "aarch64-darwin x86_64-darwin";
      flake-registry = builtins.toFile "empty-flake-registry.json" ''{"flakes":[],"version":2}'';
      max-jobs = "auto";
      trusted-users = [ "root" (if pkgs.stdenv.isDarwin then flake.config.me.username else "@wheel") ];
    };
  };
}
