name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*"
      - "**.md"
      - "!flake.nix"
      - "!flake.lock"
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    paths-ignore:
      - "*"
      - "**.md"
      - "!flake.nix"
      - "!flake.lock"
defaults:
  run:
    shell: bash
env:
  CACHIX_BINARY_CACHE: cameronraysmith
jobs:
  nixci:
    concurrency:
      group: nixci-${{ matrix.os }}-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
      cancel-in-progress: true
    strategy:
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Maximize build space
        uses: cameronraysmith/maximize-build-space@fdf0c06b18d92be98aa64cb68ae4ea4c9bc4794d # ratchet:cameronraysmith/maximize-build-space@print-usage
        with:
          build-mount-path: /nix
          build-mount-path-ownership: root:root
          root-reserve-mb: 34816
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        continue-on-error: true
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: |
         nix develop --command om ci run --systems "x86_64-linux"
      - run: df -h
